### ISSUE TITLE
Database is empty

### ISSUE THREAD

**Issue by CallousOdesa** [smartdevicelink/sdl_server#5]
Hi,

Where can I find the information how to correctly fill the DB for correct server work.

Could it be because of error due to installation described below:

fox new PoliciesServer sdl_server -- -i
info: 5. Installing sdl_server...
Cloning into 'sdl_server'...
info: 4. Creating PoliciesServer...
info: 3. Installing server modules...
info: 2. Installing client modules...
info: 1. Starting server...
[ OK ] Connected to the database.
[ OK ] Listening on port 3000 in local mode with database sdl_local.
[ INFO ] Created directory /home/amelnik/rep/PoliciesServer/client/assets/img/uploads/
Requesting data from http://140.147.249.7/standards/iso639-2/php/English_list.php
Writing to file /home/amelnik/rep/PoliciesServer/server/data/languages.js
[ INFO ] Successfully updated Language data.
Requesting data from https://raw.githubusercontent.com/datasets/country-list/master/data.csv
Writing to file /home/amelnik/rep/PoliciesServer/server/data/countries.js
[ INFO ] Successfully updated Country data.
[ 500 ] Cannot load data from invalid file location: /home/amelnik/rep/PoliciesServer/server/data/androidCategories.js

Best regards,
Andriy

**Comment by ssmereka** [comment]
Hey Andriy,  Thank you for caching a bug.

The problem was that files used to load initial database data were in all lower case instead of camel case.  For example ".../server/data/androidCategories.js" did not exist, but ".../server/data/androidcategories.js" did.  I didn't catch this because my paths are case-insensitive.

I fixed this in the repo, so you can either rename the files yourself or remove your local server and start over.  If you choose to start over make sure that you drop the current sdl_local database.

The data files are located here: [server/data/](https://github.com/smartdevicelink/sdl_server/tree/master/server/data)

**Comment by CallousOdesa** [comment]
Hi, Scott,

Thank you, now server installed successfully.

Best regards,
Andriy

**Comment by ssmereka** [comment]
you're welcome.
